SARS_PROTS = ['E',
              'M',
              'N',
              'Spike',
              'Nsp1',
              'Nsp10',
              'Nsp11',
              'Nsp12',
              'Nsp13',
              'Nsp14',
              'Nsp15',
              'Nsp2',
              'Nsp4',
              'Nsp5',
              'Nsp5 C145A',
              'Nsp6',
              'Nsp7',
              'Nsp8',
              'Nsp9',
              'Orf10',
              'Orf3a',
              'Orf3b',
              'Orf6',
              'Orf7a',
              'Orf8',
              'Orf9b',
              'Orf9c',]